In [2]:
import numpy as np
import torch

In [5]:
# Vector
nv=np.array([ [1,2,3,4] ])
print(nv), print(' ')

# Transpose
print(nv.T), print(' ')

# Transpose.Transpose
nvT=nv.T
print(nvT.T)

[[1 2 3 4]]
 
[[1]
 [2]
 [3]
 [4]]
 
[[1 2 3 4]]


In [7]:
# Matrix
nM=np.array([ [1,2,3,4],[5,6,7,8] ])
print(nM), print(' ')

# Transpose
print(nM.T), print(' ')

# Transpose.Transpose
nMT=nM.T
print(nMT.T)

[[1 2 3 4]
 [5 6 7 8]]
 
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
 
[[1 2 3 4]
 [5 6 7 8]]
