### Using Numpy

In [1]:
import numpy as np
import torch

In [2]:
# Vector
nv=np.array([ [1,2,3,4] ])
print(nv), print(' ')

# Transpose
print(nv.T), print(' ')

# Transpose.Transpose
nvT=nv.T
print(nvT.T)

[[1 2 3 4]]
 
[[1]
 [2]
 [3]
 [4]]
 
[[1 2 3 4]]


In [3]:
# Matrix
nM=np.array([ [1,2,3,4],
              [5,6,7,8] ])
print(nM), print(' ')

# Transpose
print(nM.T), print(' ')

# Transpose.Transpose
nMT=nM.T
print(nMT.T)

[[1 2 3 4]
 [5 6 7 8]]
 
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
 
[[1 2 3 4]
 [5 6 7 8]]


### Using pytorch

In [4]:
#Vector
tv=torch.tensor([ [1,2,3,4] ])
print(tv), print(' ')

# transpose
print(tv.T), print(' ')

# transpose.transpose
tvT=tv.T
print(tvT.T)

tensor([[1, 2, 3, 4]])
 
tensor([[1],
        [2],
        [3],
        [4]])
 
tensor([[1, 2, 3, 4]])


In [5]:
# Matrix
tM=torch.tensor([ [1,2,3,4],
                  [5,6,7,8] ])
print(tM), print(' ')

# Transpose
print(tM.T), print(' ')

# Transpose.Transpose
tMT=tM.T
print(tMT.T)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
 
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])
 
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [7]:
# data types
print(f'Variable nv is of type: {type(nv)}')
print(f'Variable nM is of type: {type(nM)}')
print(f'Variable tv is of type: {type(tv)}')
print(f'Variable tM is of type: {type(tM)}')

Variable nv is of type: <class 'numpy.ndarray'>
Variable nM is of type: <class 'numpy.ndarray'>
Variable tv is of type: <class 'torch.Tensor'>
Variable tM is of type: <class 'torch.Tensor'>
