In [1]:
import numpy as np
import torch
import torch.nn as nn

### Using numpy

In [3]:
v=np.array([ 1,40,2,-3 ])

# min/max values
minval=np.min(v)
maxval=np.max(v)

print(f'Min_val, max_val :{minval, maxval}')

# argmin/argmax
minidx=np.argmin(v)
maxidx=np.argmax(v)

print(f'Min,max indices: {minidx, maxidx}')

print(f'For reference, v: {v}')

# zeros indiced indices

Min_val, max_val :(np.int64(-3), np.int64(40))
Min,max indices: (np.int64(3), np.int64(1))
For reference, v: [ 1 40  2 -3]


In [4]:
# Matrices...
M=np.array([ [0,1,10],
             [20,8,5]
           ])
print(M)

# various minima in a matrix
minvals1=np.min(M) # min in entire matrix
minvals2=np.min(M,axis=0) # min of each column
minvals3=np.min(M,axis=1) # min of each row 

print(minvals1)
print(minvals2)
print(minvals3)

[[ 0  1 10]
 [20  8  5]]
0
[0 1 5]
[0 5]


In [5]:
#  minima idx
minidx1=np.argmin(M) # min from entire matrix
minidx2=np.argmin(M,axis=0) # min from each column
minidx3=np.argmin(M,axis=1) # min from each row

print(M), print(' ')
print(minidx1)
print(minidx2)
print(minidx3)

[[ 0  1 10]
 [20  8  5]]
 
0
[0 0 1]
[0 2]


### Using pytorch

In [6]:
v=torch.tensor([1,40,2,-3])

minval=torch.min(v)
maxval=torch.max(v)

print(f'Min, max values: {minval, maxval}')

# argmin, argmax
minidx=torch.argmin(v)
maxidx=torch.argmax(v)

print(f'Min, max indices: {minidx, maxidx}')

print(f'v for ref: {v}')

Min, max values: (tensor(-3), tensor(40))
Min, max indices: (tensor(3), tensor(1))
v for ref: tensor([ 1, 40,  2, -3])


In [8]:
# matrix
M=torch.tensor([[0,1,10],
                [20,8,5]])
print(M), print(' ')

# various minima
min1=torch.min(M) #min of entire
min2=torch.min(M,axis=0) # min of each column
min3=torch.min(M,axis=1) # min of each row

print(min1), print(' ')
print(min2), print(' ')
print(min2.values), print(' ')
print(min2.indices)

tensor([[ 0,  1, 10],
        [20,  8,  5]])
 
tensor(0)
 
torch.return_types.min(
values=tensor([0, 1, 5]),
indices=tensor([0, 0, 1]))
 
tensor([0, 1, 5])
 
tensor([0, 0, 1])
