In [2]:
import numpy as np
import torch

In [8]:
np.random.randn(5)

array([-0.25894595,  0.02378798,  1.17339565, -1.48609198, -1.15547419])

In [15]:
np.random.seed(17)
print(np.random.randn(5)) #randseed1 sameseq
print(np.random.randn(5)) #randseed1 same 2 up

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]


### New seed mechanism in numpy

In [21]:
randseed1=np.random.RandomState(17)
randseed2=np.random.RandomState(20210530)

print(randseed1.randn(5)) #sameseq
print(randseed2.randn(5)) #diff. but same each time
print(randseed1.randn(5)) #same 2 up
print(randseed2.randn(5)) #same 2 up
print(np.random.randn(5)) #completely different

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[-0.24972681 -1.01951826  2.23461339  0.72764703  1.2921122 ]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
[ 1.15494929 -0.0015467  -0.11196868 -1.08136725  0.10265891]
[ 0.86962384  0.56778309  0.46528234 -1.16537308 -2.03599479]


### Now pytorch

In [22]:
torch.randn(5)

tensor([ 0.1916,  0.0865,  0.0209,  0.2723, -0.6411])

In [25]:
torch.manual_seed(17)
print(torch.randn(5))

# torch seed doesnt spread to numpy
np.random.randn(5)

tensor([-1.4135,  0.2336,  0.0340,  0.3499, -0.0145])


array([ 1.1191818 , -0.98339611,  0.24452002, -0.58140974,  0.4295639 ])